name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.user.login == 'dependabot[bot]' && 'dependabot-queue' || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: dacrab/.github-workflows/.github/workflows/bun-ci.yml@557d081a9d42da0f0c69368256bcc5caf91ada61 # v1.2.0
    with:
      check-cmd: ''
      test-cmd: ''
      build-cmd: 'bun run build'

  auto-merge:
    needs: ci
    permissions:
      pull-requests: write
      contents: write
    uses: dacrab/.github-workflows/.github/workflows/dependabot-auto-merge.yml@557d081a9d42da0f0c69368256bcc5caf91ada61 # v1.2.0
    with:
      target: minor
